spring:
  datasource:
    url: jdbc:h2:file:/tmp/cojescdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database: H2

cojesc:
  restaurants:
    - name: Pod Latarniami
      id: podlatarniami
      keywords: [ 'wtorek', 'środa', 'piątek' ]
