CREATE SCHEMA COJESC;

CREATE TABLE COJESC.SAVED_MENUS (
    RESTAURANT_ID VARCHAR(100) NOT NULL,
    RESTAURANT_NAME VARCHAR(100),
    TIME_PUBLISHED VARCHAR(100),
    TIME_DOWNLOADED TIMESTAMP NOT NULL,
    CONTENT VARCHAR(10000) NOT NULL,
    PRIMARY KEY(RESTAURANT_ID)
);
